### ISSUE TITLE
PRIVATE_KEY definition

### ISSUE THREAD

**Issue by angelo-di-marzio** [flashbots/simple-arbitrage#13]
Hi !

What do you mean by 'raw 32-byte format' ?
The private key from metamask has a length of 64 char, how can i convert it to 32bytes ? 

I'm missing something here

Thanks a lot !

**Comment by cloorem** [comment]
the 64 chars are hexadecimal, so two of them is a byte.

**Comment by angelo-di-marzio** [comment]
Okay, it is indeed already a 32 byte hexa string.
