### ISSUE TITLE
Length of targets and payloads is not equal

### ISSUE THREAD

**Issue by junaid5598** [flashbots/simple-arbitrage#30]
Hi Everyone, thanks for sparing your precious time to help me.
Actually the length of my targets and payloads is not matching. I tried since more than a week but could’nt solve it. Can someone please help me come out of this issue. I would be very very happy if someone help me please. Thanking you

…
async takeCrossedMarkets(
bestCrossedMarkets: CrossedMarketDetails,
blockNumber: number,
minerRewardPercentage: number
): Promise {
for (const bestCrossedMarket of bestCrossedMarkets) {
const buyCalls =
await bestCrossedMarket.buyFromMarket.sellTokensToNextMarket(
WETH_ADDRESS,
bestCrossedMarket.volume,
bestCrossedMarket.sellToMarket
);
const inter = bestCrossedMarket.buyFromMarket.getTokensOut(
WETH_ADDRESS,
bestCrossedMarket.tokenAddress,
bestCrossedMarket.volume
);
const sellCallData = await bestCrossedMarket.sellToMarket.sellTokens(
bestCrossedMarket.tokenAddress,
inter,
this.bundleExecutorContract.address
);

  const targets: Array<string> = [
    ...buyCalls.targets,
    bestCrossedMarket.sellToMarket.marketAddress,
  ];
  const payloads: Array<string> = [...buyCalls.data, sellCallData];
…

I don’t know whether the problem is in this part of code or somewhere else. I’ve also deployed a contract on the Ethereum Mainnet.
Please someone guide me please.

**Comment by RJ-Flash** [comment]
It seems like the issue you are facing is related to the length of the targets array and the payloads array not matching.

In the code snippet you provided, you are concatenating the buyCalls.targets array and the bestCrossedMarket.sellToMarket.marketAddress into the targets array using the spread operator, and concatenating the buyCalls.data array and sellCallData into the payloads array using the spread operator as well.

If the length of buyCalls.targets and buyCalls.data arrays are not equal, then the resulting targets and payloads arrays will not have the same length.

You can add some console.log statements to check the lengths of these arrays before concatenating them to see if this is the issue. If they are not equal, you may need to modify the logic to ensure that they have the same length before concatenating them.

It's also important to ensure that the bestCrossedMarket.sellToMarket.marketAddress and sellCallData variables are of the same data type as the elements in the buyCalls.targets and buyCalls.data arrays respectively. If they are not, this could also result in a length mismatch.

**Comment by RJ-Flash** [comment]
Without knowing the specific details of the issue you're facing, I cannot provide you with a complete solution to fix your code. However, I can offer some general guidance on how to debug your issue and potentially resolve it.

From the code snippet you've provided, it appears that the targets and payloads arrays are being constructed from different sources, and you suspect that their lengths may not match. To verify this, you could add some logging statements to print out the lengths of both arrays before constructing the final transactions array:

This will print out the lengths of the buyCalls.targets, buyCalls.data, sellCallData, targets, payloads, and transactions arrays to the console, so you can see if there are any mismatches.

console.log(`buyCalls.targets length: ${buyCalls.targets.length}`);
console.log(`buyCalls.data length: ${buyCalls.data.length}`);
console.log(`sellCallData length: ${sellCallData.length}`);

const targets: Array<string> = [
  ...buyCalls.targets,
  bestCrossedMarket.sellToMarket.marketAddress,
];
const payloads: Array<string> = [...buyCalls.data, sellCallData];

console.log(`targets length: ${targets.length}`);
console.log(`payloads length: ${payloads.length}`);

const transactions = targets.map((target, i) => ({
  target,
  data: payloads[i],
  value: "0x0",
}));

console.log(`transactions length: ${transactions.length}`);

If you find that the lengths of the buyCalls.data and sellCallData arrays are not the same, you'll need to figure out why that is. One potential issue could be that the sellTokens function called on bestCrossedMarket.sellToMarket returns a different number of arguments than the sellTokensToNextMarket function called on bestCrossedMarket.buyFromMarket. You'll need to investigate the code for these functions to see if that's the case, and adjust your code accordingly.

I hope this helps! Let me know if you have any further questions.

**Comment by junaid5598** [comment]
I'm extremely sorry, I'm new to github. I didn't knew about the notifications, so I couldn't see your message. I want to Thank You from the deepest of my heart as you spared your precious time for me. Actually I was just working on this project (FlashBots with Robert Miller), I didn't create it. After working and trying to understand this project for a long time, I realized that I can't figure out properly about what's all going inside it. So I left that project and headed towards some easy projects. I'm still feeling extremely sorry for your precious time that got wasted because of me. I'm just feeling helpless as I'm unable to compensate for the loss of your precious time and energy behind me. I just want to say  I'm Sorry.
