### ISSUE TITLE
Why is UniswappyV2EthPair.uniswapInterface a UNISWAP_PAIR_ABI contract on WETH_ADDRESS?

### ISSUE THREAD

**Issue by hengruo** [flashbots/simple-arbitrage#37]
code src/UniswappyV2EthPair.ts line 25.

`static uniswapInterface = new Contract(WETH_ADDRESS, UNISWAP_PAIR_ABI);`

WETH_ADDRESS is an ERC20 token, how can it match UNISWAP_PAIR_ABI?

**Comment by ignoracenfly** [comment]
您的邮件已经收到。谢谢

**Comment by ignoracenfly** [comment]
您的邮件已经收到。谢谢
