### ISSUE TITLE
Minor: Orphaned link in README.md

### ISSUE THREAD

**Issue by jachiang** [flashbots/simple-arbitrage#8]
The link to `Flashbots Searcher FAQ` in README.md seems to be orphaned: https://hackmd.io/@flashbots/rk-qzgzCD

**Comment by N0K0** [comment]
Same link is also broken in the source
https://github.com/flashbots/simple-arbitrage/blob/master/src/index.ts#L28

**Comment by obadiaa** [comment]
Updated! This is the latest version to refer to: https://github.com/flashbots/pm/blob/main/guides/searcher-onboarding.md
Thank you! :)
